##################################################
# Application
##################################################

spring.application.name=api-gateway

##################################################
# Server
##################################################

server.port=8080

##################################################
# Eureka
##################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

##################################################
# Gateway Discovery
##################################################

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

##################################################
# JWT
##################################################

jwt.secret=OrderFlowSuperSecretKeyForDevelopmentOnlyChangeThisInProduction123456789

##################################################
# Auth Service Route
##################################################

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

##################################################
# Product Service Route
##################################################

spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**

##################################################
# Order Service Route
##################################################

spring.cloud.gateway.server.webflux.routes[2].id=order-service

spring.cloud.gateway.server.webflux.routes[2].uri=lb://ORDER-SERVICE

spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**

##################################################
# Inventory Service Route
##################################################

spring.cloud.gateway.server.webflux.routes[3].id=inventory-service

spring.cloud.gateway.server.webflux.routes[3].uri=lb://INVENTORY-SERVICE

spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.server.webflux.routes[4].id=payment-service

spring.cloud.gateway.server.webflux.routes[4].uri=lb://PAYMENT-SERVICE

spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/payments/**

####################################################
# Actuator / Observability
####################################################

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}