spring.application.name=payment-service

server.port=8086


####################################################
# Eureka
####################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


####################################################
# MySQL
####################################################

spring.datasource.url=jdbc:mysql://localhost:3306/orderflow_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


####################################################
# JPA
####################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


####################################################
# Kafka
####################################################

spring.kafka.bootstrap-servers=localhost:9092


####################################################
# Kafka Producer
####################################################

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


####################################################
# Actuator / Observability
####################################################

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}